require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MusoraTemplatesExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-safe-area-context', :path => '../../node_modules/react-native-safe-area-context'
  pod 'RNCAsyncStorage', :path => '../../node_modules/@react-native-async-storage/async-storage'
  pod 'RNSVG', :path => '../../node_modules/react-native-svg'
  pod 'RNKeychain', :path => '../../node_modules/react-native-keychain'
  pod 'RNDeviceInfo', :path => '../../node_modules/react-native-device-info'
  pod 'react-native-orientation-locker', :path => '../../node_modules/react-native-orientation-locker'
  pod 'react-native-add-calendar-event', :path => '../../node_modules/react-native-add-calendar-event'
  pod 'RNImageCropPicker', :path => '../../node_modules/react-native-image-crop-picker'
  pod 'RNGestureHandler', :path => '../../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', :path => '../../node_modules/react-native-reanimated'
  pod 'RNScreens', :path => '../../node_modules/react-native-screens'
  pod 'RNDeviceInfo', :path => '../../node_modules/react-native-device-info'
  pod 'react-native-background-downloader', :path => '../../node_modules/react-native-background-downloader'
  pod 'react-native-netinfo', :path => '../../node_modules/@react-native-community/netinfo'
  pod 'rn-fetch-blob', :path => '../../node_modules/rn-fetch-blob'
  pod 'RNRate', :path => '../../node_modules/react-native-rate'
  pod 'RNPDF', :path => '../../node_modules/react-native-view-pdf'
  pod 'react-native-webview', :path => '../../node_modules/react-native-webview'
  pod 'react-native-google-cast', :path => '../../node_modules/react-native-google-cast/ios'
  pod 'react-native-video', :path => '../../node_modules/react-native-video'
  pod 'RNIap', :path => '../../node_modules/react-native-iap'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
